DROP TABLE IF EXISTS documents;
CREATE TABLE documents (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  doc_id TEXT NOT NULL,
  doc_text TEXT NOT NULL
);

DROP TABLE IF EXISTS matches;
CREATE TABLE matches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  doc_id TEXT NOT NULL,
  stem TEXT NOT NULL,
  matches TEXT NOT NULL
);
